name: Tests

on:
  push:
    branches:
      - test

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_pgsql, rdkafka, opentelemetry
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test

      - name: Create an issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          test: duplicate
          sha: ${{ steps.AWS.outputs.GITHUB_SHA_SHORT }}
          error: ${{ steps.mvn_test_error.outputs.msg }}
          error_short: ${{ steps.mvn_test_error_short.outputs.msg }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: open

      - name: pull-request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MYWORKFLOW  }}
        with:
          source_branch: "test"
          destination_branch: "main"
          pr_title: ${{ github.event.head_commit.message }}
          pr_body: ${{ github.event.head_commit.message }}
          pr_label: "Staging,TestsPassed"
          pr_assignee: "damouu"

      - name: move youtrack-test-failed
        if: ${{ failure() }}
        uses: bloobirds-it/action-youtrack-move@v1.0.0
        with:
          github-token: ${{ secrets.MyWorkflow }}
          yt-url: ${{ secrets.YOUTRACK_URL }}
          yt-token: ${{ secrets.YOUTRACK_TOKEN }}
          yt-project-id: "LAN"
          yt-column-triggers: "Test"
          yt-column-target: "TestFailed"
